version: '3.7'

services:

  sample-prod:
    container_name: sample-prod
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - '1337:80'
    env_file:
      - .env