version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - '../:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      WATCHPACK_POLLING: "true"